version: "2"

services:
  mongo:
    image: bitnami/mongodb:latest
    container_name: ${PROJECT_NAME}-mongo
    hostname: mongo.${MONGO_HOST}
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - MONGODB_DATABASE=${MONGODB_DATABASE}
    restart: "always"

  backend:
    image: <REGISTORY_URL>
    container_name: ${PROJECT_NAME}-backend
    env_file: .env
    command: gunicorn -c /opt/code/gunicorn.conf.py project.wsgi:application
    depends_on:
      - mongo
    links:
      - mongo
    restart: always

  nginx:
    image: <REGISTORY_URL>
    env_file: .env
    container_name: ${PROJECT_NAME}-nginx
    entrypoint:
      - /opt/bin/entrypoint.sh
    command: nginx
    links:
      - backend
    depends_on:
      - backend
    ports:
      - ${SERVER_PORT}:80
    environment:
      - SERVER_HOST=backend
      - SERVER_PORT=8000
    restart: always
